global:
  scrape_interval: 3s # Par défaut, scrape toutes les 15 secondes.
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
